### ISSUE TITLE
Reminder to self!

### ISSUE THREAD

**Issue by woon-seng-hong-xinmin** [pendragons-code/LISBDIE#1]
Yes same person as pendragon, but i can't log in lmao, since o school pc!

spam from wordlist
json config
bash script for linux users!
Update grammatical errors since the time you decided to upload this was a sub-optimal timing for neural functions.

**Comment by pendragons-code** [comment]
To implement json config method in 3.5

**Comment by woon-seng-hong-xinmin** [comment]
Tested on chromebook 2nd gen lenovo 500e (something like that, but it is the 8GB RAM variant) CPU usages goes up to 50% and 90 % peak.

Test components:
Sentence to be spammed: "The quick brown fox jumps over the lazy dog."
Number of repetitions: 5000
Delay between each message: 0

CPU usage includes the other tasks as what i am also looking for is the total usage, also i could not find the instance as i had to run it using the IDE and not natively.


Benchmarks!

keystrokes replication:
Time to complete 5000 sets: 43 seconds
Average CPU and RAM usage: 76% and 400MiB
Peak CPU: 91%
Peak RAM: 692 MiB

Pasting method (no formatting, ctrl v method as middle click is used for something else on chrome OS):
Time to complete: 37 seconds
Average CPU and RAM usage: 86% and 538 MiB
Peak CPU: 100%
Peak RAM: 736 MiB

Spam by file (content replication by typing):
Time to complete 5000 sets: 52 seconds
Average CPU and RAM usage: 100% and 900MiB
Peak CPU: 100%
Peak RAM: 1.2GiB

Will consider optimising if running the same test on another PC gets results that shows evidence of high usage, but to be fair tho, it is a lousy chromebook so lol!

**Comment by woon-seng-hong-xinmin** [comment]
add documentation for windows users (DO NOT INCLUDE THE INSTALL PROCESS)

(additional stuff: add links to aur and libraries, talk about the installation (manual) and include a bash file to work the whole download process. )

**Comment by pendragons-code** [comment]
items to be implemented soon: install script, json config.

**Comment by pendragons-code** [comment]
There was a typo for the benchmark. It seems that the test components are inaccurate. We need to do a retest soon!

**Comment by pendragons-code** [comment]
Benchmarks are up to date
