### ISSUE TITLE
Parse Int in the input variable itself instead of making a new one?

### ISSUE THREAD

**Issue by javiers-code** [pendragons-code/LISBDIE#8]
# micro optimization might help boost performance LISBDIE
example:
```
c = input("Countdown?: ")
count = int(c)
```
this can be changed to
```
c = int(input("Countdown?: ")
```

**Comment by pendragons-code** [comment]
this was actually something i did in v3, but i got some inconsistency on error reporting, so i reverted to an older version of v3. Sure i'll make the changes.

**Comment by pendragons-code** [comment]
> this was actually something i did in v3, but i got some inconsistency on error reporting, so i reverted to an older version of v3. Sure i'll make the changes.

This was actually related to something else that was fixed later on, forgot to change it back, also at the same time, in v6 i will be implementing burst fire.

**Comment by pendragons-code** [comment]
But is should also be noted that it might actually work in my interest here since i could choose to do something when it is a string before parsing the integer. I'll see where the heck this project goes.
